[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
#
# Testing.
#
env = "echo $ANCHOR_PROVIDER_URL"
test = "npm run test"
test-with-build = "anchor run build && anchor test --skip-build"
#
# Build the program and all CPI dependencies.
#
build = "anchor run build-deps && anchor build"
build-deps = "anchor run build-name-service && anchor run build-metadata"
build-name-service = "cd deps/solana-program-library/name-service/program && pwd && cargo build-bpf && cd ../../../../"
build-metadata = "cd deps/metaplex/rust/token-metadata/program && pwd && cargo build-bpf && cd ../../../"

[[test.genesis]]
address = "namesLPneVptA9Z5rqUDD9tMTWEJwofgaYwp8cawRkX"
program = "./deps/solana-program-library/target/deploy/spl_name_service.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex/rust/target/deploy/spl_token_metadata.so"

[workspace]
members = ["programs/spl-token-bonding", "programs/spl-token-collective", "programs/spl-token-staking"]

[programs.mainnet]
spl_token_bonding = "Ep23h6U7HvBb2NRGRTxxH5mekpV4V3b6AJh76mra5Yiv"
spl_token_collective = "TCo1sP6RwuCuyHPHjxgzcrq4dX4BKf9oRQ3aJMcdFry"
spl_token_staking = "TStakXwvzEZiK6PSNpXuNx6wEsKc93NtSaMxmcqG6qP"

[programs.localnet]
spl_token_bonding = "Ep23h6U7HvBb2NRGRTxxH5mekpV4V3b6AJh76mra5Yiv"
spl_token_collective = "TCo1sP6RwuCuyHPHjxgzcrq4dX4BKf9oRQ3aJMcdFry"
spl_token_staking = "TStakXwvzEZiK6PSNpXuNx6wEsKc93NtSaMxmcqG6qP"
