name: Mainnet Proposal

on:
  push:
    tags:       
      - 'v**'
env:
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1

jobs:
  create-bonding-proposal:
    name: Create Bonding Proposal
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-with-gov-proposal/
        id: deploy
        with:
          program: spl_token_bonding
          program-id: TBondmkCYxaPCKG4CHYfVTcwQ8on31xnJrPzk8F8WsS
          network: mainnet
          keypair: ${{ secrets.DEPLOY_KEYPAIR }}
          governance: HDkW3MrrvqT9FPvuFBAVnSag1BLDx767MD2VXKfpCoCe
          name: Deploy ${{ github.ref_name }}
          description: https://github.com/StrataFoundation/strata/tree/${{ github.ref_name }}
      - uses: ./.github/actions/anchor-publish/
        with:
          program: spl_token_bonding
          anchor-token: ${{ secrets.ANCHOR_TOKEN }}
